Repository 2TEAM-Ideality/be14-final-Ideality-CoreFlow-front, pull requests merged in 2025-06, with the labels that each got.

#3 [SETTING] 레이아웃 및 페이지 세팅
  package-lock.json
  package.json
  src/App.vue
  src/assets/logo.png
  src/assets/vue-flow-style.css
  src/components/common/BreadCrumb.vue
  src/components/common/TheHeader.vue
  src/components/layout/ApprovalLayout.vue
  src/components/layout/BasicLayout.vue
  src/components/layout/CalendarLayout.vue
  src/components/layout/ListLayout.vue
  src/components/layout/ProjectLayout.vue
  src/components/project/DelayLogTab.vue
  src/components/project/GanttTab.vue
  src/components/project/MemberListTab.vue
  src/components/project/OverviewTab.vue
  src/components/project/PipelineTab.vue
  src/components/project/ResourceSearchTab.vue
  src/main.js
  src/plugins/vuetify.js
  src/router/index.js
  src/views/Home.vue
  src/views/approval/Approval.vue
  src/views/calendar/Calendar.vue
  src/views/project/ProjectDetail.vue
  src/views/project/ProjectList.vue
  src/views/template/CreateTemplate.vue
  src/views/template/EditTemplate.vue
  src/views/template/EditTemplateTask.vue
  src/views/template/TemplateDetail.vue
  src/views/template/TemplateList.vue
  src/views/test/CustomNode.vue
  src/views/test/Icon.vue
  src/views/test/PipePage.vue
  src/views/test/initial-elements.js
  src/views/test/test-elements.js
  src/views/test/useLayout.js
  src/views/user/Login.vue
Labels: ⚙️ Setting

#6 [feat] 로그인 화면 및 헤더 유저 부분 구현
  package-lock.json
  package.json
  public/images/profile/defaultProfile.png
  src/App.vue
  src/components/common/LoadingModal.vue
  src/components/common/TheHeader.vue
  src/components/user/FindPwdModal.vue
  src/components/user/LoginModal.vue
  src/stores/userStore.js
  src/views/user/Login.vue
  vite.config.js
Labels: ✨ Feature

#8 [SETTING] 헤더에 자동으로 토큰 붙여서 전송 세팅
  src/api.js
Labels: ⚙️ Setting

#9 [FEAT] SSE 연결
  src/App.vue
  src/assets/icons/ring.png
  src/components/common/NotificationSidebar.vue
  src/components/common/TheHeader.vue
  src/components/common/useNotifications.js
  src/stores/notificationStore.js
  src/stores/userStore.js
Labels: ✨ Feature

#12 [Feat] 관리자 구성원 관리 페이지 구현
  package-lock.json
  package.json
  src/App.vue
  src/api.js
  src/components/admin/AdminSideBar.vue
  src/components/admin/CreatePartner.vue
  src/components/admin/CreateUser.vue
  src/components/admin/DeptTree.vue
  src/components/admin/ManagingOrg.vue
  src/components/admin/ManagingUser.vue
  src/components/common/TheHeader.vue
  src/components/user/ChangePwdModal.vue
  src/components/user/FindPwdModal.vue
  src/components/user/LoginModal.vue
  src/components/user/UserInfo.vue
  src/router/index.js
  src/stores/userStore.js
  src/views/admin/Admin.vue
Labels: ✨ Feature

#27 [FEAT] 프로젝트 목록 조회
  package-lock.json
  package.json
  src/components/common/DonutChart.vue
  src/components/project/ProjectCard.vue
  src/plugins/vuetify.js
  src/router/index.js
  src/views/project/ProjectList.vue
Labels: ✨ Feature

#40 [Feat] 결재 페이지 구현
  src/App.vue
  src/components/admin/CreatePartner.vue
  src/components/admin/CreateUser.vue
  src/components/admin/DeptTree.vue
  src/components/approval/ApprovalDetails.vue
  src/components/approval/ApprovalHistory.vue
  src/components/approval/CreateApproval.vue
  src/components/approval/ParticipantSelectModal.vue
  src/components/common/TheHeader.vue
  src/components/layout/ApprovalLayout.vue
  src/components/user/UserInfo.vue
  src/views/approval/Approval.vue
Labels: ✨ Feature

#42 [REFACTOR] 리프레시 토큰을 쿠키 방식으로 변경
  src/api.js
  src/components/common/TheHeader.vue
  src/components/user/LoginModal.vue
  src/router/index.js
  src/stores/userStore.js
  src/views/master/ErpMaster.vue
Labels: 🛠️ Refactor

#43 [Schedule] 부서 일정 페이지 조회만 연결& 구현
  src/components/admin/DeptTree.vue
  src/components/common/NewTaskModal.vue
  src/components/common/TheHeader.vue
  src/components/flow/TaskNode.vue
  src/components/layout/CalendarLayout.vue
  src/components/project/PipelineTab.vue
  src/components/project/ProjectStatusButton.vue
  src/components/schedule/TodaySchedule.vue
  src/components/user/MyProfileModal.vue
  src/components/user/UserInfo.vue
  src/data/dummySchedule.js
  src/views/calendar/Calendar.vue
  src/views/project/ProjectDetail.vue
Labels: ✨ Feature, 🎨 Design

#49 [Style] 결재 상세 조회 스타일 수정
  src/components/admin/ManagingUser.vue
  src/components/approval/ApprovalDetails.vue
  src/components/approval/ApprovalHistory.vue
  src/components/approval/CreateApproval.vue
  src/components/approval/ParticipantSelectModal.vue
  src/components/user/UserInfo.vue
  src/stores/userStore.js
  src/views/approval/Approval.vue
  src/views/master/ErpMaster.vue
Labels: 🎨 Design

#50 [FEAT] 프로젝트 오버뷰 페이지
  src/components/common/UserInfoCard.vue
  src/components/project/OverviewTab.vue
  src/components/project/SummaryCard.vue
  src/views/project/ProjectDetail.vue
Labels: ✨ Feature

#52 [FEAT] 세부일정
  src/components/details/DetailCreateModal.vue
  src/components/details/DetailPage.vue
  src/components/details/Modal.vue
  src/components/project/GanttTab.vue
  src/components/project/data-source.js
  src/components/task/DetailModal.vue
  src/components/task/DetailTab.vue
  src/components/task/TaskMainTab.vue
  src/main.js
  src/views/project/ProjectDetail.vue
  src/views/task/TaskDetail.vue
Labels: ✨ Feature

#56 [FEAT] 참여자 목록 구현 완료
  src/components/project/MemberListTab.vue
Labels: ✨ Feature

#57 [FEAT] 간트 조회 구현
  src/components/project/GanttTab.vue
  src/components/user/ChangePwdModal.vue
  src/stores/userStore.js
  src/views/approval/Approval.vue
  src/views/home/Home.vue
Labels: ✨ Feature

#58 [FEAT] 태스크 상세 페이지, 댓글 페이지 구현 완료
  src/components/common/ConfirmModal.vue
  src/components/task/CommentTab.vue
  src/components/task/NoticeTab.vue
  src/components/task/SidebarCommentSection.vue
  src/components/task/TaskApprovalTab.vue
  src/components/task/TaskAttachmentTab.vue
  src/components/task/TaskCommentInput.vue
  src/components/task/TaskHeaderSection.vue
  src/components/task/TaskInfoTab.vue
  src/components/task/TaskMainTab.vue
  src/views/task/TaskDetail.vue
Labels: ✨ Feature, 🎨 Design

#59 [FEAT] 세부일정 생성수정조회
  src/components/task/DetailModal.vue
  src/components/task/DetailTab.vue
  src/components/task/EditModal.vue
  src/components/task/TaskMainTab.vue
  src/stores/taskStore.js
Labels: ✨ Feature

#67 [REFACTOR] 결재 검색바 생성
  src/components/approval/ApprovalHistory.vue
  src/stores/userStore.js
  src/views/master/ErpMaster.vue
Labels: ✨ Feature, 🛠️ Refactor

#65 [REFACTOR] 코드 리팩토링
  src/components/common/NotificationSidebar.vue
  src/components/common/TheHeader.vue
  src/components/task/DetailModal.vue
  src/components/task/DetailTab.vue
  src/components/task/TaskMainTab.vue
  src/stores/taskStore.js
  src/views/task/TaskDetail.vue
Labels: 🛠️ Refactor

#69 [FEAT] 프로젝트 생성 페이지, 홈화면 마감 임박 알림 연결
  src/components/approval/CreateApproval.vue
  src/components/approval/ParticipantSelectModal.vue
  src/components/home/RecentIssue.vue
  src/components/home/TodaySchedule.vue
  src/components/project/ProjectStatusButton.vue
  src/components/project/SelectTemplateModal.vue
  src/components/task/TaskInfoTab.vue
  src/views/calendar/Calendar.vue
  src/views/home/Home.vue
  src/views/project/CreateProject.vue
Labels: ✨ Feature, 🛠️ Refactor

#70 [FEAT] 알림 읽음처리 및 해당 알림 클릭시 라우팅
  src/App.vue
  src/components/common/NotificationSidebar.vue
  src/components/common/TheHeader.vue
  src/components/task/DetailModal.vue
  src/stores/notificationStore.js
Labels: ✨ Feature

#74 [FIX] 프로젝트 생성 시 템플릿 적용 문제 해결
  src/components/common/NewTaskModal.vue
  src/components/project/PipelineTab.vue
  src/views/project/CreateProject.vue
Labels: 👾 Bug, 🛠️ Refactor

#75 [FIX] 세부일정 생성 안됨 문제 해결
  src/components/task/TaskMainTab.vue
Labels: 👾 Bug, 🛠️ Refactor

#76 [FIX] 메인 데이터 연결 및 프로젝트 생성 각종 수정
  src/components/approval/CreateApproval.vue
  src/components/common/NewTaskModal.vue
  src/components/home/RecentIssue.vue
  src/components/project/PipelineTab.vue
  src/components/task/CommentTab.vue
  src/components/task/TaskInfoTab.vue
  src/components/task/TaskMainTab.vue
  src/views/project/CreateProject.vue
  src/views/task/TaskDetail.vue
Labels: 👾 Bug

#77 [FIX] 공휴일 반영 완료
  src/components/approval/ParticipantSelectModal.vue
  src/components/flow/TaskNode.vue
  src/components/home/RecentIssue.vue
  src/components/project/PipelineTab.vue
  src/components/task/DetailTab.vue
  src/components/task/TaskInfoTab.vue
  src/components/task/TaskMainTab.vue
  src/views/project/CreateProject.vue
Labels: 👾 Bug

#79 [BUG]세부일정 관련 버그 총 수정
  src/components/task/DetailModal.vue
  src/components/task/DetailTab.vue
  src/components/task/TaskMainTab.vue
  src/stores/taskStore.js
  src/views/task/TaskDetail.vue
Labels: 👾 Bug

#80 [FIX] 태스크 생성 /수정 관련 에러 해결
  src/components/common/NewTaskModal.vue
  src/components/project/PipelineTab.vue
  src/plugins/vuetify.js
  src/stores/holidayStore.js
  src/views/project/CreateProject.vue
Labels: 👾 Bug, 🛠️ Refactor

#83 [FIX] 태스크 작동 문제 해결 완료
  src/components/common/NewTaskModal.vue
  src/components/project/PipelineTab.vue
  src/components/project/TaskButton.vue
  src/components/task/TaskHeaderSection.vue
  src/components/task/TaskInfoTab.vue
Labels: 👾 Bug, ✨ Feature, 🛠️ Refactor

#86 [STYLE] 경과율, 진척율 폰트 크기 조절
  src/components/flow/TaskNode.vue
Labels: 🎨 Design

#88 [REFACTOR] 댓글 부분 script 개선
  src/components/common/ListForm.vue
  src/components/task/CommentTab.vue
  src/components/task/NoticeTab.vue
  src/components/task/TaskCommentInput.vue
Labels: 🛠️ Refactor

#90 [REFACTOR] 수정
  index.html
  package-lock.json
  package.json
  src/assets/data/warning-dummy.json
  src/assets/square-logo.png
  src/components/approval/ApprovalHistory.vue
  src/components/approval/CreateApproval.vue
  src/components/approval/ParticipantSelectModal.vue
  src/components/common/EmptyState.vue
  src/components/common/ListForm.vue
  src/components/common/Loading.vue
  src/components/common/TheHeader.vue
  src/components/flow/TaskNode.vue
  src/components/home/RecentIssue.vue
  src/components/project/AttachmentList.vue
  src/components/project/DelayLogTab.vue
  src/components/project/MemberListTab.vue
  src/components/project/PipelineTab.vue
  src/components/project/ProjectCard.vue
  src/components/project/ReportPreviewModal.vue
  src/components/project/TaskButton.vue
  src/components/task/DetailModal.vue
  src/components/task/DetailTab.vue
  src/components/task/TaskAttachmentTab.vue
  src/components/task/TaskCommentInput.vue
  src/components/task/TaskDonutChart.vue
  src/components/task/TaskHeaderSection.vue
  src/components/task/TaskInfoTab.vue
  src/components/task/TaskMainTab.vue
  src/components/user/LoginModal.vue
  src/router/index.js
  src/stores/taskStore.js
  src/stores/updateStore.js
  src/views/approval/NewApproval.vue
  src/views/home/Home.vue
  src/views/master/ErpMaster.vue
  src/views/task/TaskDetail.vue
  src/views/template/EditTemplate.vue
  src/views/template/TemplateList.vue
  src/views/test/PipePage.vue
Labels: 👾 Bug, ✨ Feature, 🎨 Design, 🛠️ Refactor

#91 [REFACTOR] 세부일정 수정 모드 취소 버튼
  src/api.js
  src/components/task/DetailModal.vue
  src/components/task/DetailTab.vue
  src/stores/userStore.js
Labels: 🛠️ Refactor

#94 [REFACTOR] 결제 페이지 분리 및 UI 수정
  src/components/approval/ApprovalDetails.vue
  src/components/approval/ApprovalHistory.vue
  src/components/approval/CreateApproval.vue
  src/components/layout/ApprovalLayoutTwo.vue
  src/components/layout/BasicLayout.vue
  src/components/task/DetailModal.vue
  src/components/task/DetailTab.vue
  src/components/user/LoginModal.vue
  src/router/index.js
  src/views/approval/Approval.vue
  src/views/approval/NewApproval.vue
  src/views/project/CreateProject.vue
  src/views/template/CreateTemplate.vue
  src/views/test/PipePage.vue
Labels: 🎨 Design, 🛠️ Refactor

#95 [REFACTOR] 바뀐 조회대로 프사 조회되게 완료
  src/components/common/TheHeader.vue
  src/components/common/UserInfoCard.vue
  src/components/task/CommentTab.vue
  src/components/task/TaskCommentInput.vue
  src/components/task/TaskInfoTab.vue
Labels: 🛠️ Refactor

#98 [FIX] 어드민 뜨는 문제 해결
  src/components/project/MemberListTab.vue
Labels: 👾 Bug

#100 [REFACTOR] 세부일정 부서목록 수정(수정중)
  src/components/task/DetailModal.vue
  src/components/task/TaskInfoTab.vue
  src/components/task/TaskMainTab.vue
Labels: 🛠️ Refactor

#101 [REFACTOR] 다운로드 되게 변경
  src/components/approval/CreateApproval.vue
  src/components/common/ListForm.vue
  src/components/task/CommentTab.vue
Labels: 🛠️ Refactor

#107 [REFACTOR]아이콘수정
  src/components/task/DetailTab.vue
Labels: 🛠️ Refactor

#105 [REFACTOR] vite.config 수정
  vite.config.js
Labels: 🌎 Deploy

#109 [REFACTOR] 템플릿 프로젝트에서 duration, slackTime 추출
  src/views/template/CreateTemplate.vue
Labels: ✨ Feature, 🛠️ Refactor

#111 [refactor] 태스크 완료 모달 수정
  src/components/task/CompleteTaskModal.vue
  src/views/task/TaskDetail.vue
Labels: ✨ Feature, 🛠️ Refactor

#114 [REFACTOR] 태스크 완료 모달 수정
  src/components/flow/TaskNode.vue
  src/components/project/TaskButton.vue
  src/components/task/CompleteTaskModal.vue
Labels: 👾 Bug, 🛠️ Refactor

#113 FIX : 태스크 세부 페이지 - 예상 시작/종료일 예외처리
  src/components/flow/TaskNode.vue
  src/components/project/DelayLogTab.vue
  src/components/task/DetailModal.vue
  src/components/task/TaskInfoTab.vue
  src/components/task/TaskMainTab.vue
  src/stores/updateStore.js
  src/views/task/TaskDetail.vue
Labels: 🛠️ Refactor

#116 [REFACTOR] 표시되는 날짜 수정 / 완료된 건 수정 불가
  src/components/task/DetailModal.vue
  src/components/task/TaskInfoTab.vue
Labels: 🛠️ Refactor

#118 FIX: 템플릿 수정
  src/views/calendar/Calendar.vue
  src/views/template/EditTemplate.vue
  src/views/test/CustomNode.vue
  src/views/test/PipePage.vue
Labels: 👾 Bug

#119 [REFACTOR] 태스크 초대 모달 연결 완료
  src/components/approval/ParticipantSelectModal.vue
  src/components/project/MemberListTab.vue
  src/components/task/TaskParticipantTab.vue
Labels: 🛠️ Refactor

#120 [REFACTOR] 초대할 때 예외터지게
  src/components/project/MemberListTab.vue
  src/components/task/TaskParticipantTab.vue
Labels: 🛠️ Refactor

#121 [REFACTOR] 태스크 내부에 최신순 안나오던거 마지막 정렬
  src/components/task/TaskAttachmentTab.vue
Labels: 🛠️ Refactor

#123 [REFACTOR] release 브랜치 활용으로 변경
  .github/workflows/deploy.yml
Labels: 🌎 Deploy

#125 refactor 프로젝트 생성 시 템플릿 정보 수정
  src/components/approval/CreateApproval.vue
  src/views/project/CreateProject.vue
Labels: 🛠️ Refactor

#127 [REFACTOR] 결재 요청 시 예상 변경일 확인
  src/components/approval/CreateApproval.vue
  src/components/flow/TaskNode.vue
Labels: 🛠️ Refactor
